Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/julia/Desktop/Seraina_Zeug/joeynmt/joeynmt/__main__.py", line 61, in <module>
    main()
  File "/mnt/c/Users/julia/Desktop/Seraina_Zeug/joeynmt/joeynmt/__main__.py", line 41, in main
    train(cfg_file=args.config_path, skip_test=args.skip_test)
  File "/mnt/c/Users/julia/Desktop/Seraina_Zeug/joeynmt/joeynmt/training.py", line 791, in train
    cfg = load_config(Path(cfg_file))
  File "/mnt/c/Users/julia/Desktop/Seraina_Zeug/joeynmt/joeynmt/helpers.py", line 171, in load_config
    with path.open("r", encoding="utf-8") as ymlfile:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: 'scripts/../configs/transformer_sample_config_word-level.yaml'
